### ISSUE TITLE
Add `product_name` in all languages

### ISSUE THREAD

**Issue by jeremyarancio** [openfoodfacts/openfoodfacts-exports#9]
### Problem
We got a request to get the product name in all languages instead of just the `world` one.

![Image](https://github.com/user-attachments/assets/3c210ed4-8f7e-4e15-ba9a-1c61bfed8551)

### Proposed solution
Add columns `product_name_{..}`

**Comment by raphael0202** [comment]
I added it last week :)

![Image](https://github.com/user-attachments/assets/9bffd93b-eb1f-493e-90e7-82d37347a3b2)

It's not done yet for `generic_name` though. And what is the `name` field? It's the first time I hear about it.
